import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from './components/Header'
import Hero from './components/Hero'
import Reception from './components/Reception'
import Table from './components/Table'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Shayan Hotel Server</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/hotellogo.png" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Reception />
        <Table />
      </main>
    </>
  );
}
